<?php

namespace AppBundle\Repository;

/**
 * toolCheckoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class toolCheckoutRepository extends \Doctrine\ORM\EntityRepository
{
}
