<?php

namespace AppBundle\Repository;

/**
 * toolStoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class toolStoreRepository extends \Doctrine\ORM\EntityRepository
{
	public function removeTools($toolId, $toolsRemoved) {
		$toolStore = $this->getEntityManager()->getRepository('AppBundle:toolStore')->findOneBy(array( 'toolId' => $toolId ));
		$toolStore->setQuantity(($toolStore->getQuantity() - $toolsRemoved));
	}
	
	public function addTools($toolId, $toolsRemoved) {
		$toolStore = $this->getEntityManager()->getRepository('AppBundle:toolStore')->findOneBy(array( 'toolId' => $toolId ));
		$toolStore->setQuantity(($toolStore->getQuantity() + $toolsRemoved));
	}
}