<?php

namespace AppBundle\Repository;

/**
 * toolTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class toolTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
